### ISSUE TITLE
when doing an update - also have the ability to generate a git short log for each ci component

### ISSUE THREAD

**Issue by kapilt** [sethvargo/ratchet#18]
### TL;DR

when pinning stuff we always have to update eventually, for bug fixes, features, security. but auditing those updates is also a key aspect, one simple facility that would make that nicer is for ratchet to generate a changelog.md on the updates (via git checkout and short log on the delta between the two revisions), which can then be used in a pull request description/comment to help reviewers on the updates.

**Comment by sethvargo** [comment]
Hi @kapilt 

Unfortunately we can't easily do that for two reasons:

1. If a ref is pinned to a floating tag (like `main`), the delta isn't meaningful.

2. No such "diff" exists for containers.

I think we could print out a summary at the end of the original -> updated values, but I don't think it'd be useful to construct diffs, since that will be highly platform dependent (and Ratchet will likely expand to support multiple CI/CD workflow systems).

**Comment by kapilt** [comment]
I think I that's fair and in practice, using ratchet, with dependbot updates on actions does generate the needed context on accepting updates re changelings as well automating the cron/update aspect.
